### ISSUE TITLE
snmptrap plug in is not mapping the complete mib name

### ISSUE THREAD

**Issue by anjilinga** [logstash-plugins/logstash-input-snmptrap#38]
HI,

We are using snmp trap in put plugin to recieve the trap and yaml mapping files to replace he oids with mib name.

in trap we are having the value as 1.3.6.1.2.1.15.3.1.2,

it should replace the value is bgppeerstate, but it is replacing as bgp.3.1.2

The part of yaml file si below. as bgp is coming first it is replacing it even though the below one is exact match. can you please suggest how to fix it.

bgp: 1.3.6.1.2.1.15
bgpVersion: 1.3.6.1.2.1.15.1
bgpLocalAs: 1.3.6.1.2.1.15.2
bgpPeerTable: 1.3.6.1.2.1.15.3
bgpPeerEntry: 1.3.6.1.2.1.15.3.1
bgpPeerIdentifier: 1.3.6.1.2.1.15.3.1.1
bgpPeerState: 1.3.6.1.2.1.15.3.1.2
bgpPeerAdminStatus: 1.3.6.1.2.1.15.3.1.3
bgpPeerNegotiatedVersion: 1.3.6.1.2.1.15.3.1.4
bgpPeerLocalAddr: 1.3.6.1.2.1.15.3.1.5
bgpPeerLocalPort: 1.3.6.1.2.1.15.3.1.6
bgpPeerRemoteAddr: 1.3.6.1.2.1.15.3.1.7

Logstash version is : 7.17
Logstah is running as docker container.

**Comment by edmocosta** [comment]
I couldn't reproduce this issue on the current plugin's version. It seems the problem was already fixed. When the given MIB yaml file is provided, the OID gets mapped as `<file-name>::bgpPeerState`, which is the expected behaviour. 

Logstash has a new SNMP [integration plugin](https://github.com/logstash-plugins/logstash-integration-snmp) that replaces this individual one, and will be bundled by default with Logstash in the future. If you're still facing this issue, I suggest you to upgrade to the integration plugin ([migration guide](https://github.com/logstash-plugins/logstash-integration-snmp/blob/main/docs/index.asciidoc#migrating-to-logstash-integration-snmp-from-individual-plugins)).

Please feel free to re-open this issue if the problem still persists. Thanks!
